---
- name: Openshift Origin On oVirt
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yaml

  roles:
    - role: openshift_ovirt

- import_playbook: setup_dns.yaml
- import_playbook: deploy_ovirt_storage_driver.yaml
