---
- name: Openshift Origin On oVirt
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yaml

  roles:
    - role: openshift_ovirt

- import_playbook: setup_dns.yaml
- import_playbook: playbooks/prerequisites.yml
- import_playbook: playbooks/openshift-node/network_manager.yml
- import_playbook: playbooks/deploy_cluster.yml
