kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ovirt-provisioner
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: ovirt-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ovirt-provisioner
  apiGroup: rbac.authorization.k8s.io
